[package]
name = "text-blind-watermark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"

[lib]
name = "text_blind_watermark"
path = "src/lib.rs"