[package]
name = "text-blind-watermark"
version = "0.1.0"
edition = "2021"
authors = ["Guo Fei <me@guofei.site>"]
description = "Text Blind Watermark in Rust"
license = "MIT"

[dependencies]
rand = "0.8.5"

[lib]
name = "text_blind_watermark"
path = "src/lib.rs"